name: supabase_error_translator_flutter
description: >-
  Translate Supabase error codes into user-friendly messages in 9 languages. 
  Perfect for international Flutter apps with automatic language detection and robust fallback system.
version: 1.0.1
homepage: https://github.com/mrehman29/supabase_error_translator_flutter
repository: https://github.com/mrehman29/supabase_error_translator_flutter
issue_tracker: https://github.com/mrehman29/supabase_error_translator_flutter/issues
documentation: https://github.com/mrehman29/supabase_error_translator_flutter#readme

topics:
  - supabase
  - error-handling
  - internationalization
  - i18n
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

funding:
  - https://github.com/sponsors/mrehman29
  - https://www.buymeacoffee.com/mrehman29

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
